### PR TITLE
Fix: compatibility PHP 7.2 & Nette Utils 2.5

### PR DESCRIPTION
**Pull request by JanGalek**

### CODE REVIEW

**Comment by lookyman** [comment]
You can drop PHP 5 and HHVM support, and add 7.1 and 7.2 please.

**Comment by JanGalek** [comment]
ok, updated.

I asked for Deprecated in SmartObject with ObjectMixin in slack -  https://pehapkari.slack.com/archives/C2R30BLKA/p1519048342000093 and will be fixed in nette/utils 2.5.1

**Comment by lookyman** [comment]
Actually I think we can drop SmartObject trait usage as well..

**Comment by JanGalek** [comment]
Drop will not help, becase you use Container which use abstract Nette\ComponentModel\Component which use SmartObject.

EDIT: @dg fixed it ;)

**Comment by JanGalek** [comment]
@lookyman is everything ok ? :)

**Comment by dg** [comment]
Why it has conflict with nette utils 2.5?

**Comment by JanGalek** [comment]
thx

**Pull request merged**
